### ISSUE TITLE
Cannot rename when connected to IoT Device

### ISSUE THREAD

**Issue by GregPettyjohn** [Microsoft/WindowsDevicePortalWrapper#180]
For IoT, I was able to connect but then subsequently ran into a failure when requesting the device name. I sent along the stack trace to Hirsch and he was able to reproduce this:
[<unknown>] There was an error deserializing the object of type Microsoft.Tools.WindowsDevicePortal.DevicePortal+DeviceName. Encountered unexpected character '<'.
[<unknown>]    at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream)
   at Microsoft.Tools.WindowsDevicePortal.DevicePortal.<Get>d__253`1.MoveNext() in D:\GitRepos\WindowsDevicePortalWrapper\WindowsDevicePortalWrapper\WindowsDevicePortalWrapper.Shared\HttpRest\RestGet.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Tools.WindowsDevicePortal.DevicePortal.<GetDeviceName>d__74.MoveNext() in D:\GitRepos\WindowsDevicePortalWrapper\WindowsDevicePortalWrapper\WindowsDevicePortalWrapper.Shared\Core\OsInformation.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SampleDeviceCollection.DevicePortalViewModel.<RefreshDeviceNameAsync>d__36.MoveNext() in D:\GitRepos\WindowsDevicePortalWrapper\Samples\SampleDeviceCollection\ViewModels\DevicePortalViewModel.cs:line 349

**Comment by hpsin** [comment]
@namkedia can you take a look at this?
